[package]
name = "mf_rust"
version = "0.1.0"
authors = ["Fensiss"]
edition = "2018"

[dependencies]
gdnative = "0.9.1"
rand = "0.7.3"
uuid = {version = "0.8.1", features = ["v4"]}

[lib]
crate-type = ["cdylib"]